import StaticHeader from '@/components/common/FixedHeader/StaticHeader';
import Footer from '@/components/common/Footer/Footer';
import Header from '@/components/common/Header/Header';
import '@/styles/index.scss';

export const metadata = {
  title: 'ABDK',
  description: 'Generated by AI',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Footer />
        </body>
    </html>
  )
}
